// // import { Geist, Geist_Mono, Poppins } from "next/font/google";
// // import "./globals.css";
// // import Navbar from "@/components/layouts/Navbar";
// // import Footer from "@/components/layouts/Footer";
// // import NextAuthProvider from "@/provider/NextAuthProvider";

// // const poppings = Poppins(
// //   {
// //     weight: ["100", "200", "400", "500", "600", "800"],
// //   }
// // )

// // export const metadata = {
// //   title: "BeautyMart",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <NextAuthProvider>

// //       <html
// //       lang="en"
// //       className={`${poppings.className} antialiased`}
// //     >
// //       <body className="min-h-full flex flex-col">

// //         <header className="py-2 md:w-11/12 mx-auto">

// //           <Navbar></Navbar>

// //         </header>
       
// //        <main className="py-2 md:w-11/12 mx-auto min-h-[calc(100svh-302px)] "> {children}</main>

// //         <Footer></Footer>
        
// //         </body>
// //     </html>

    
// //     </NextAuthProvider>
// //   );
// // }
// import { Poppins } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/layouts/Navbar";
// import Footer from "@/components/layouts/Footer";
// import NextAuthProvider from "@/provider/NextAuthProvider";

// const poppins = Poppins({
//   weight: ["100", "200", "400", "500", "600", "800"],
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "BeautyMart",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={`${poppins.className} antialiased`}>
//       <body className="min-h-full flex flex-col">

//         <NextAuthProvider>
//           <header className="py-2 md:w-11/12 mx-auto">
//             <Navbar />
//           </header>

//           <main className="py-2 md:w-11/12 mx-auto min-h-[calc(100svh-302px)]">
//             {children}
//           </main>

//           <Footer />
//         </NextAuthProvider>

//       </body>
//     </html>
//   );
// }



import { Poppins } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "BeautyMart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="min-h-screen flex flex-col antialiased">

        {/* NEXT AUTH CONTEXT */}
        <NextAuthProvider>

          {/* HEADER */}
          <header className="py-2 md:w-11/12 mx-auto">
            <Navbar />
          </header>

          {/* MAIN CONTENT */}
          <main className="flex-1 py-2 md:w-11/12 mx-auto">
            {children}
          </main>

          {/* FOOTER */}
          <Footer />

        </NextAuthProvider>

      </body>
    </html>
  );
}