// import Products from "@/components/home/Products";
// import React from "react";

// export const metadata = {
//   title: "All Products",
//   description: "Generated by create next app",
// };
// const ProductsPage = () => {
//   return (
//     <div>
//       <Products></Products>
//     </div>
//   );
// };

// export default ProductsPage;

import Products from "@/components/home/Products";
import { getProducts } from "@/actions/server/product";
import React from "react";

export const metadata = {
  title: "All Products",
  description: "Generated by create next app",
};

const ProductsPage = async () => {
  const products = await getProducts();

  return (
    <div>
      <Products products={products} />
    </div>
  );
};

export default ProductsPage;